spring:
  datasource:
    url: jdbc:mysql://192.168.190.131:3306/stu_system?characterEncoding=utf8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 设置动态代理的方式 true jdk代理， false cglib代理
  aop:
    proxy-target-class: true
  mvc:
    favicon:
      enable: false
# 设置 Mybatis 的 xml 保存路径
mybatis-plus:
  type-aliases-package: com.example.stusystem.model.pojo
  global-config:
    db-config:
      id-type: auto # 全局id类型为自增长
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


knife4j:
  enable: true
  openapi:
    title: 学生管理系统
    description:  学生管理系统
    email: xiaoymin@foxmail.com
    concat: 八一菜刀
    url: https://docs.xiaominfo.com
    version: v4.0
    group:
      teacher:
        group-name: teacher
        api-rule: package
        api-rule-resources:
          - com.example.subsystem.controller.teacher
      student:
        group-name: student
        api-rule: package
        api-rule-resources:
          - com.example.subsystem.controller.student